groq/openbench

- src/openbench/_cli/eval_command.py
- src/openbench/_registry.py
- src/openbench/utils/imports.py
Decided I'd have a crack at refactoring this project to support a design I think would better support my use-case (wanting to work on my own evals without patching `openbench` itself). So I thought I'd start by implementing this:
```
bench eval ./local-path
```
To start, we could implement all the built-in evals e.g. `bench eval xyz` by saying that `xyz` is just an alias to a directory inside `openbench`. That required a bit of moving things around and my python skills are pretty limited, so this might not be right, but I've started by:
* Made an `evals` directory in the root of the project (instead of being within `src/openbench/{datasets,evals,scorers}`)
* Each `eval` exports a `__metadata__` property which captures the stuff that used to be in `src/openbench/config.py`
* The evals …
> Adding `bench eval ./local-path` to support people writing their own evals

- src/openbench/_registry.py
- src/openbench/model/_providers/nebius.py
- Add Nebius as a new OpenAI-compatible model provider
- Follows the same implementation pattern as Cerebras and SambaNova providers
- Uses Nebius Studio API endpoint at https://api.studio.nebius.com/v1
> feat: add Nebius model provider

- src/openbench/_registry.py
- src/openbench/model/_providers/nous.py
- Add Nous Research as a new OpenAI-compatible model provider
- Uses prefix `nous/` for model names
- API endpoint: https://inference-api.nousresearch.com/v1
- Follows the same implementation pattern as other OpenAI-compatible providers
> feat: add Nous Research model provider

- README.md
- src/openbench/_registry.py
- src/openbench/model/_providers/huggingface.py
This PR implements an API class that exposes hugging face inference providers in a more native way. 
It allows for this:
```bash
export HF_TOKEN=hf_xxx
bench eval mmlu --model huggingface/openai/gpt-oss-120b
bench eval mmlu --model huggingface/openai/gpt-oss-120b:groq
```
> [FEATURE] Add hugging face inference providers

- pyproject.toml
- src/openbench/_cli/eval_command.py
- src/openbench/_cli/utils.py
- uv.lock
- Ports the `-M` and `-T` flags from inspect_ai CLI to openbench for consistency
- Enables passing dynamic model and task arguments on a case-by-case basis
- **Add `-M` flag**: Pass native model arguments (e.g., `-M temperature=0.5 -M max_tokens=100`)
- **Add `-T` flag**: Pass task arguments (e.g., `-T dataset_size=10 -T shuffle=true`)
- **Environment variable support**: `BENCH_MODEL_ARGS` and `BENCH_TASK_ARGS`
- **Utility function**: Added `parse_cli_args()` to handle key=value argument parsing with YAML type conversion
```bash
bench eval mmlu --model openai/gpt-4 -M temperature=0.5 -M max_tokens=100
bench eval humaneval --model openai/gpt-4 -T dataset_size=50 -T timeout=30
bench eval mmlu --model openai/gpt-4 -M temperature=0.7 -M seed=42 -T subset=astronomy
```
These flags match the …
> feat: add -M and -T flags for model and task arguments

- CONTRIBUTING.md
- Fixed incorrect directory paths in CONTRIBUTING.md that were inconsistent with actual project structure
- Updated from `src/bench/` to `src/openbench/`
- Removed README requirement for individual eval folders since config.py is used instead
- Updated benchmark addition instructions to reflect correct directory structure
- Aligned example structure with actual project layout
- Added reference to config.py for benchmark metadata registration
Per discussion in Slack, the CONTRIBUTING.md had outdated directory structure documentation (lines 144-160) that needed updating.
> docs: fix directory structure documentation in CONTRIBUTING.md

- src/openbench/_registry.py
- src/openbench/model/_providers/hyperbolic.py
- Add support for Hyperbolic as a new inference provider in OpenBench
- Implement OpenAI-compatible API interface for seamless integration
- Enable usage with `hyperbolic/` model prefix
- Created `HyperbolicAPI` class extending `OpenAICompatibleAPI`
- Registered provider in `_registry.py` for automatic model routing
- Support for environment variables: `HYPERBOLIC_API_KEY` and `HYPERBOLIC_BASE_URL`
- Default base URL: `https://api.hyperbolic.xyz/v1`
```bash
export HYPERBOLIC_API_KEY=your_key
bench eval mmlu --model hyperbolic/your-model-name --limit 10
```
> feat: add Hyperbolic inference provider

- src/openbench/_registry.py
- src/openbench/model/_providers/crusoe.py
- Add support for Crusoe AI cloud infrastructure provider
- Implements OpenAI-compatible API interface
- Uses CRUSOE_API_KEY environment variable for authentication
> feat: add Crusoe inference provider

- src/openbench/_registry.py
- src/openbench/model/_providers/deepinfra.py
- Add support for DeepInfra scalable inference infrastructure
- Implements OpenAI-compatible API interface
- Uses DEEPINFRA_API_KEY environment variable for authentication
> feat: add DeepInfra inference provider

- src/openbench/_registry.py
- src/openbench/model/_providers/minimax.py
- Add support for MiniMax AI model infrastructure
- Implements OpenAI-compatible API interface
- Uses MINIMAX_API_KEY environment variable for authentication
> feat: add MiniMax inference provider

- src/openbench/_registry.py
- src/openbench/model/_providers/cohere.py
- Add support for Cohere enterprise-ready language model infrastructure
- Implements OpenAI-compatible API interface
- Uses COHERE_API_KEY environment variable for authentication
> feat: add Cohere inference provider

- .gitignore
- src/openbench/evals/gpqa_diamond.py
- src/openbench/evals/matharena/matharena.py
- src/openbench/scorers/__init__.py
- src/openbench/scorers/robust_boxed.py
- src/openbench/scorers/robust_mcq.py
- tests/test_robust_scorers.py
- Adds robust MCQ and boxed answer extraction scorers adapted from gpt-oss
- Updates GPQA and AIME evaluations to use the more robust scorers
- Adds comprehensive test coverage for the new extraction logic
The existing scorers had limited pattern matching capabilities, causing valid answers to be marked incorrect when models used different formatting. This PR ports the comprehensive answer extraction logic from gpt-oss to make evaluations more reliable.
1. **New Scorers**:
- `robust_mcq_scorer`: Handles 11+ MCQ answer formats (markdown, LaTeX, parentheses, etc.)
- `robust_boxed_scorer`: Extracts from `\boxed{}`, `\fbox{}`, `\framebox{}` with fallback
- `aime_scorer`: Specialized for AIME math problems with range validation
2. **Updated Evaluations**:
- GPQA Diamond now uses …
> feat: add robust answer extraction scorers from gpt-oss

- CLAUDE.md
- CONTRIBUTING.md
- pyproject.toml
- uv.lock
- Unpinned all dependencies except `inspect-ai` to allow uv to resolve the latest compatible versions
- `inspect-ai` remains pinned at version 0.3.115 for stability
This allows the project to benefit from bug fixes and improvements in dependencies while maintaining flexibility for version resolution through uv's dependency resolver.
> chore: unpin dependencies except inspect-ai

- README.md
- src/openbench/config.py
- src/openbench/datasets/cti_bench.py
- src/openbench/evals/cti_bench.py
- src/openbench/scorers/cti_bench.py
Adds CTI-Bench, a cybersecurity benchmark with 5 specialized tasks for evaluating LLMs on cyber threat intelligence:  MITRE ATT&CK technique extraction, multiple-choice CTI knowledge, CVE-to-CWE mapping, and CVSS scoring.
[https://github.com/xashru/cti-bench](url)
> feat: add CTI-Bench cybersecurity benchmark suite

- pyproject.toml
- src/openbench/config.py
- src/openbench/datasets/browsecomp.py
- src/openbench/evals/browsecomp.py
- src/openbench/scorers/browsecomp.py
- uv.lock
- Implements BrowseComp (A Simple Yet Challenging Benchmark for Browsing Agents) from [simple-evals](https://github.com/openai/simple-evals)
- Adds comprehensive browsing-related benchmark with 1,266 questions that evaluate model performance on web content understanding and reasoning tasks
- Fixes a bug in the original simple-evals implementation (regex extraction issue)
1. **Dataset Loader** (`src/openbench/datasets/browsecomp.py`)
- Loads encrypted dataset from OpenAI's public blob storage
- Implements XOR decryption for questions and answers using canary values
- Formats questions with required response template
2. **Scorer** (`src/openbench/scorers/browsecomp.py`)
- Model-graded scoring using gpt-4.1-2025-04-14 by default
- Preserves exact grading template from original implementation …
> feat: add BrowseComp benchmark

- .github/workflows/ci.yml
- Fix "All Checks Pass" job to properly handle skipped integration tests for external PRs
- Fix test coverage path from incorrect 'bench' to correct 'openbench' package name
The CI was incorrectly failing when integration tests were skipped (which happens for external contributors' PRs from forks). This made it appear that external PRs were failing CI when they were actually fine.
- Updated the "All Checks Pass" job logic to treat skipped integration tests as acceptable
- Fixed the pytest coverage path to use the correct package name 'openbench' instead of 'bench'
> fix: handle skipped integration tests in CI

- src/openbench/scorers/rootly_gmcq.py
- Fixed AttributeError in rootly_gmcq scorer when message content is a list
- Added proper handling for both string and list content types using the .text property
> fix(rootly_gmcq): handle both string and list content types in scorer

- release-please-config.json
Configure release-please to only increment minor version on breaking changes before v1.0.0.
- Set `bump-minor-pre-major: false` to prevent regular features from bumping minor version
- Set `bump-patch-for-minor-pre-major: true` to make features bump patch version instead
**Before v1.0.0:**
- `feat:` commits → patch version bump (was minor)  
- `fix:` commits → patch version bump (unchanged)
- `feat!:`/`fix!:` commits → minor version bump (was major)
**After v1.0.0:**
- Standard semver behavior applies (`feat:` → minor, `feat!:` → major)
> feat: configure release-please for pre-v1.0 version bumping

- src/openbench/datasets/graphwalks.py
- src/openbench/evals/graphwalks.py
- src/openbench/scorers/graphwalks.py
Adds optional token-count–based filtering to the GraphWalks dataset pipeline.
Samples that exceed user-specified max_context_size are now dropped during dataset preparation, constraining evals to contexts within a token budget.
- Extended record_to_sample in graphwalks.py to:
- Compute input token counts via get_token_count.
- Drop records whose token length exceeds max_context_size.
- Attach raw_input_tok_cnt to sample metadata for downstream metrics 
- Updated get_dataset to accept max_context_size and pass it through to the mapper.
This feature mirrors the MRCR evaluation’s token gating strategy, but is adapted for GraphWalks.
It provides a consistent mechanism for controlling dataset size relative to model context limits, and sets up future work on token-binned scoring.
> feat: graphwalks token filter

- README.md
- src/openbench/_cli/eval_command.py
- Changes the default model from `groq/meta-llama/llama-4-scout-17b-16e-instruct` to `groq/openai/gpt-oss-20b`
- Updates CLI default in `src/openbench/_cli/eval_command.py`
- Updates documentation in README.md to reflect the new default in both configuration examples and CLI options table
> feat: change default model to groq/openai/gpt-oss-20b

- src/openbench/_registry.py
- src/openbench/model/_providers/groq.py
Add support reasoning_effort support for GPT-OSS models on Groq. The `--reasoning-effort` flag (supported within groq.py, OpenBench's modified implementation of Inspect's implementation) can be used to specify the degree of reasoning effort for GPT-OSS models on Groq. Models that do not support reasoning_effort will simply ignore the flag.
Additionally, fixed a bug where the "groq/" model provider still defaulted to Inspect's implementation. Now we simply override Inspect's registry _registry["modelapi:inspect_ai/groq"] with OpenBench's implementation in groq.py.
- Fixed a bug where the "groq/" model provider still defaulted to Inspect's implementation. Now we simply override Inspect's registry _registry["modelapi:inspect_ai/groq"] with OpenBench's implementation in groq.py. …
> feat: groq reasoning effort + bugfix to override inspect's "groq"

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- scripts/make_clockbench_data.py
- src/openbench/_registry.py
- src/openbench/config.py
- src/openbench/datasets/clockbench.py
- src/openbench/evals/clockbench.py
- src/openbench/scorers/clockbench.py
**Summary**
Adds Clockbench, a challenging multimodal evaluation that tests models' ability to read analog clocks and perform temporal reasoning. Evaluates visual perception (reading clock faces) and temporal arithmetic (time calculations).
**What's Added**
scripts/make_clockbench_dataset.py
- creates synthesized data parquet by unpacking public input.json, answer .json, and image files.
- output parquet contains the following fields: "id", "image" (bytes), "file_name", "question_time", "question_shift", "question_angle", "question_zone", "answer_time", "answer_shift", "answer_angle", "answer_zone"
datasets/clockbench.py: 
- sample extraction from hf dataset (parquet)
scorers/clockbench.py:
- follows original benchmark implementation scoring logic to provide metrics including …
> feat: add clockbench evaluation framwork and script for synthesizing public dataset.

- src/openbench/monkeypatch/display_results_patch.py
Builds on existing display results monkeypatch to reconstruct the Inspect AI display results panel. The display results panel now can include custom fields, such as average task duration, p50, and p95. See attached images for before and after
- Building on top of existing monkeypatch at display_results_patch.py to add custom display results following an eval's completion
- [] I have added tests that prove my fix is effective or that my feature works
Before:
After:
*p50 > mean indicates a left-skewed distribution. This makes sense with aime_2025, since there are some very fast tasks pulling the average below the median.
> feat: display results patch to include task duration stats

- src/openbench/model/_providers/openrouter.py
Adds support for the following Openrouter provider routing args: https://openrouter.ai/docs/features/provider-routing
- Add support for new -M flags for Openrouter routing args
- Inject these arg flags into the Openrouter request
Closes #
Example showing the flag -M only=providername
> feat(openrouter): add provider routing args support
